import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Script from 'next/script'
import MyHome from '@/components/MyHome'
import MySkills from '@/components/MySkills'
import MyExperience from '@/components/MyExperience'
import MyUIWorks from '@/components/MyUIWorks'
import MyUXWorks from '@/components/MyUXWorks'
import MyAchievements from '@/components/MyAchievements'
import MyContact from '@/components/MyContact'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>GFolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.css" rel="stylesheet" />
      </Head>
      <main>
        <Navbar/>
        <MyHome/>
        <MySkills/>
        <MyUIWorks/>
        <MyUXWorks/>
        <MyExperience/>
        <MyAchievements/>
        <MyContact/>
        <Footer/>
      </main>
      <footer>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js" />
        <Script src="https://unpkg.com/aos@next/dist/aos.js"/>
      </footer>
    </>
  )
}
